#IMAGEN BASE PARA NO TOMAR TODO DE PYTHON
FROM python:3.10.4-slim-bullseye

#SETEAR VARIABLES DE ENTORNO
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#SETEAR DIRECTORIO DE TRABAJO
WORKDIR /code

#INSTALAR DEPENDENCIA O COPIAR EL ARCHIVO DE DEPENDENCIAS
COPY ./requirements.txt .
RUN pip install -r requirements.txt

#COPIAR EL PROYECTO- todo lo que tenemos en el proyecto lo COPIE EN EL DIRECTORIO DE TRABAJO /CODE
COPY . .