services:
  web:
    build: .
    ports:
      #HABILITAMOS EL PUERTO INTERNO DEL CONTENEDOR, PODEMOS ACCEDER DESDE EL PUERO EXTERNO 8000
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
